<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Application\BUnited.Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\Infrastructure\BUnited.Modules.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\Contracts\BUnited.Modules.Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Security\BUnited.BuildingBlocks.Security.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
